### ISSUE TITLE
generating styles from a tailwind.config.js

### ISSUE THREAD

**Issue by Ziinc** [MythicalFish/react-native-tailwind#1]
do you think that it will be possible to [generate the reference stylesheet](https://github.com/MythicalFish/react-native-tailwind/blob/master/src/lib/tailwind.js) dynamically from a `tailwind.config.js` generated from the tailwindcss cli?

**Comment by Ziinc** [comment]
I think we might be able to leverage the default plugin configurations here:

https://github.com/tailwindcss/tailwindcss/blob/master/src/defaultPlugins.js

https://github.com/tailwindcss/tailwindcss/tree/master/src/plugins

**Comment by MythicalFish** [comment]
That's an interesting idea :) Unfortunately I don't have much free time to work on this at the moment, but if you have a go at this let me know
