### ISSUE TITLE
Tailwind Version

### ISSUE THREAD

**Issue by austriker27** [MythicalFish/react-native-tailwind#15]
What version of tailwind does this run? Does it run 1.0? 

It looks like it might not be maintained anymore.

**Comment by MythicalFish** [comment]
I'm using this with a pet project which I've (very) slowly been working on for the last couple of years. I do intend to update & improve it eventually. I'm also accepting PRs :)

**Comment by austriker27** [comment]
Gotcha. What version of tailwind does it use so if I use it I know which docs to reference? 

I'm not sure I have the bandwidth but I'll keep that in mind. Thanks for the answer!

**Comment by MythicalFish** [comment]
I think it must be around `0.7.3`, I'm not 100% sure, but you can also lookup the classNames in this file:
https://github.com/MythicalFish/react-native-tailwind/blob/master/src/lib/tailwind.js

I really should try to update this repo, looks like people are using it!

:)

**Comment by MythicalFish** [comment]
I updated the colors! 
Might have the motivation to do more today :)

**Comment by austriker27** [comment]
@MythicalFish Awesome!
