### ISSUE TITLE
Readme file link file removed 

### ISSUE THREAD

**Issue by jasonleonhard** [MythicalFish/react-native-tailwind#16]
https://github.com/MythicalFish/react-native-tailwind/blob/master/src/tailwind.js

Was removed and now supported styles are not accessible

commit 35e76630ddbf08eea788b0a1ba15a5ea6f43e44b
Author: Jake <jake@mythical.fish>
Date:   Sun Mar 29 15:19:24 2020 +0200

**Comment by didwiz** [comment]
@jasonleonhard check if this might help you: https://github.com/MythicalFish/react-native-tailwind/blob/master/src/tailwind/index.js

**Comment by MythicalFish** [comment]
Oops, fixed! :)
